/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Model.RegistrarKm;
import Db.RegistrarKmDao;
import java.sql.SQLException;
import javax.swing.JOptionPane;
public class RegistrarKmVisual extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarKm
     */
    public RegistrarKmVisual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        lblPatente = new javax.swing.JLabel();
        lblNombreConductor = new javax.swing.JLabel();
        lblKilometraje = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtPatente = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtNombreConductor = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtKilometraje = new javax.swing.JTextPane();
        btnRegistrar = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPatente.setText("Patente:");

        lblNombreConductor.setText("Nombre conductor");

        lblKilometraje.setText("Kilometraje:");

        jScrollPane4.setViewportView(txtPatente);

        jScrollPane5.setViewportView(txtNombreConductor);

        jScrollPane6.setViewportView(txtKilometraje);

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreConductor)
                    .addComponent(lblPatente)
                    .addComponent(lblKilometraje))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)))
                        .addGap(223, 223, 223))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnRegistrar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPatente)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreConductor)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKilometraje)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92)
                .addComponent(btnRegistrar)
                .addContainerGap(203, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed


    String patente = txtPatente.getText();
    String conductor = txtNombreConductor.getText();
    String kilometraje = txtKilometraje.getText();

    // Validaciones básicas en la interfaz 
    if (patente == null || patente.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese la patente del camión.", "Error", JOptionPane.WARNING_MESSAGE);
        txtPatente.requestFocus();
        return;
    }
    if (conductor == null || conductor.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese el nombre del conductor.", "Error", JOptionPane.WARNING_MESSAGE);
        txtNombreConductor.requestFocus();
        return;
    }
    if (kilometraje == null || kilometraje.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese el kilometraje.", "Error", JOptionPane.WARNING_MESSAGE);
        txtKilometraje.requestFocus();
        return;
    }

    //(Opcional) comprobar que el kilometraje parezca un número — DAO acepta String, pero es útil avisar
    try {
        Integer.parseInt(kilometraje.trim());
    } catch (NumberFormatException ex) {
        int opcion = JOptionPane.showConfirmDialog(this,
            "El kilometraje no parece un número entero. ¿Deseas guardarlo igual?",
            "Kilometraje no numérico",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
        if (opcion != JOptionPane.YES_OPTION) {
            txtKilometraje.requestFocus();
            return;
        }
    }


    RegistrarKm registro = new RegistrarKm();
    registro.setPatenteCamion(patente.trim());
    registro.setNombreConductor(conductor.trim());
    registro.setKilometraje(kilometraje.trim()); 

    RegistrarKmDao dao = new RegistrarKmDao();
    try {
        dao.insertar(registro); 
        JOptionPane.showMessageDialog(this, "Kilometraje registrado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);


        txtPatente.setText("");
        txtNombreConductor.setText("");
        txtKilometraje.setText("");
        txtPatente.requestFocus();

    } catch (SQLException sqle) {

        JOptionPane.showMessageDialog(this, "Error al guardar en la base de datos:\n" + sqle.getMessage(),
                                      "Error BD", JOptionPane.ERROR_MESSAGE);
        sqle.printStackTrace();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error inesperado:\n" + e.getMessage(),
                                      "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
    

    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarKm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarKm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarKm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarKm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

/* Create and display the form */
java.awt.EventQueue.invokeLater(new Runnable() {
    public void run() {
        new RegistrarKmVisual().setVisible(true);
    }
});
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblKilometraje;
    private javax.swing.JLabel lblNombreConductor;
    private javax.swing.JLabel lblPatente;
    private javax.swing.JTextPane txtKilometraje;
    private javax.swing.JTextPane txtNombreConductor;
    private javax.swing.JTextPane txtPatente;
    // End of variables declaration//GEN-END:variables
}
